### ISSUE TITLE
How to use this library

### ISSUE THREAD

**Issue by wuyingfeng1992** [beniTrainor/chrome-extension-library#1]

**Comment by beniTrainor** [comment]
Hey!

Well, there's no actual library at the moment. But my goal is to bring together pieces from existing projects to improve the development of Chrome extensions.

I'm guessing that it won't be very different from other existing projects. So, if you're looking for a stable library I suggest you look at some the ones I have listed in the [README](https://github.com/beniTrainor/chrome-extension-library).

I mainly want to develop this library to have more knowledge and control over the code that I deliver to clients. I don't want to simply pick up something I find on GitHub. Once I have something stable and worthwhile sharing I will put it up on this repo.

I hope this answer your question. Let me know if you want more details.
